### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by davidperrenoud** [gcrabtree/react-native-socketio#20]
@gcrabtree: You wrote on a couple of days ago that you're currently working on upgrading to Swift 2.3. Will you also support Swift 3?

@JohnKim, @algesten: Do you already have a fork working with Swift 3?

**Comment by algesten** [comment]
not me. i decided to keep my project in swift2 until this is solved.

**Comment by gcrabtree** [comment]
@davidperrenoud Not planning on Swift 3 just yet.

**Comment by prashen** [comment]
macos high sierra 10.13.4
I am using xcode Version 9.4
"react": "^16.3.0-alpha.1",
"react-native": "0.54.4",
node v8.9.3
npm 5.5.1
inside swift language version it's showing two verions of swift 3.3 and 4.1 so i am using 3.3

it's giving me error.
so just kindly say anyone will this plugin support my updated configuration???
