### ISSUE TITLE
Where to import SocketIO from?

### ISSUE THREAD

**Issue by thngdude** [gcrabtree/react-native-socketio#22]
Sorry if this seems trivial, but I can't figure it out: Where do you import SocketIO from in the example?

`var socket = new SocketIO('localhost:3000', socketConfig);`

If I do

`import SocketIO from 'react-native-socketio'`

I get "Cannot read property 'initialize' of undefined" error.

**Comment by thngdude** [comment]
Silly mistake of not installing via instructions.

**Comment by LucasSouzaa** [comment]
I'm getting this error and I don't know where I'm going wrong

**Comment by krunalp1993** [comment]
@thngdude @LucasSouzaa Can you describe how it got working? I am following same instructions as docs. but, still not working for me.

Please help me.
