### ISSUE TITLE
Not compatible with react-native init?

### ISSUE THREAD

**Issue by 8enmann** [gcrabtree/react-native-socketio#24]
Objective-C Bridging Header doesn't exist. After Googling it, it seems I need to create a new build target with Swift as the language choice. But will this break my React stuff?

**Comment by davidperrenoud** [comment]
Objective-C Bridging Header should exist under _Build Settings_. You don't need to create a new build target or use Swift for your app.

Note that you cannot use Xcode 8 right now with `react-native-socketio`, but you can use `socket.io-client` instead:
https://github.com/gcrabtree/react-native-socketio/issues/19#issuecomment-249481813

**Comment by 8enmann** [comment]
Ah, I'm using xcode 8. Switched to socket.io-client and it worked
perfectly. Thanks!
