### ISSUE TITLE
Android installation issue

### ISSUE THREAD

**Issue by salmenlinna** [gcrabtree/react-native-socketio#6]
error: package com.github.gcrabtree.rctsocketio does not exist
import com.github.gcrabtree.rctsocketio.SocketIoPackage;

The correct location of the package (in MainActivity.java) is:
import com.gcrabtree.rctsocketio.SocketIoPackage;

**Comment by BigPun86** [comment]
+1

**Comment by gcrabtree** [comment]
Thanks for pointing that out.
